[package]
name = "eascrow"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "22.0.5" }

[dev-dependencies]
soroban-sdk = { version = "22.0.5", features = ["testutils"] }